// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsTrader.Infrastructure.Persistence;

#nullable disable

namespace OptionsTrader.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617120109_AddTradeFields")]
    partial class AddTradeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptionsTrader.Domain.Entities.BrokerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrokerName")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BrokerSettings");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("S3Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Broker")
                        .HasColumnType("int");

                    b.Property<int>("Contracts")
                        .HasColumnType("int");

                    b.Property<int>("DailyTradeNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OptionType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Pnl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PnlPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpotPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$yC0FPNRVNuCnx4QXzOvwxudPB.ELdE1JCgA1XXq.uUMVJaQHRS1Mu",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$WutdB2SqpkGVYUfgwq.RB.oflAva/BvO7OrZRbgsSn6Cz49nkI9g.",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$NDZssu4Cwl2qvCNmli3s1e57tQdd4xn0K4.o1fUA6qytE6VdUZkuq",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$l8Swuuidp.DeWvuIsafyYuMCrfP.gPpXKh/cIurS4kSWgS3kd3gMK",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$7z8lMqzqES6r5nKDyWjq1.2eFmVDUcOzy0xtnVq9F6b94LYlbT.jm",
                            Username = "user5"
                        });
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Screenshot", b =>
                {
                    b.HasOne("OptionsTrader.Domain.Entities.Trade", "Trade")
                        .WithMany("Screenshots")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
