// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsTrader.Infrastructure.Persistence;

#nullable disable

namespace OptionsTrader.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617120133_AddTradeFieldsPrecision")]
    partial class AddTradeFieldsPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptionsTrader.Domain.Entities.BrokerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrokerName")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BrokerSettings");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("S3Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Broker")
                        .HasColumnType("int");

                    b.Property<int>("Contracts")
                        .HasColumnType("int");

                    b.Property<int>("DailyTradeNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OptionType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PnlPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpotPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$dgDv.f7A33xAsaWPn99PUOR9nGr1BYnE8ZbCoEN.O5ND5B3fTN0zS",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$taLofYtpXX1XG.iRsxcbouKURNU0EktEu8NTqZBUlazx1jvp21Ngm",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$pm9IkQDUERzv06oAbDCRAuxG9CIHBuEb8riZag4/ye4.KD.c3e06i",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$.XmU.jW8rviT7crJuwODCOU9S3f8kvUKo0eMfaIDrzJGWfQxh7hmy",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$g0BVhNXTwYwLqSVY8WoWaumOe.ffdrT05eBn/7E9k7zprVcQXP/NK",
                            Username = "user5"
                        });
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Screenshot", b =>
                {
                    b.HasOne("OptionsTrader.Domain.Entities.Trade", "Trade")
                        .WithMany("Screenshots")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("OptionsTrader.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
